register(GRAMPLET,
        id="Related Relatives Gramplet",
        name=_("Related Relatives Gramplet"),
        description = _("Gramplet showing relatives in a relation"),
        status = STABLE,
        fname="RelatedRelativesGramplet.py",
        height=230,
        expand=True,
        gramplet = 'RelatedRelativesGramplet',
        gramplet_title=_("Related Relatives"),
        version = '1.0.3',
        gramps_target_version="3.3",
        )
