sidebar_list = ["RelationshipView", 
                "EventView", 
                "FamilyView",
                "FanChartView",
                "GeoView",
                "HtmlView",
                "MediaView",
                "NoteView",
                "PedigreeView",
                "PersonListView",
                "PersonTreeView",
                "PlaceListView",
                "PlaceTreeView",
                "RepositoryView",
                "SourceView"]

for name in sidebar_list:
    register(VIEW, 
             id    = '%sSidebar' % name,
             name  = _("%s Sidebar") % _(name),
             category = ("Splitviews", _("Splitviews")),
             description =  _("%s with a Gramplet Sidebar") % name,
             version = '1.1',
             gramps_target_version = '3.3',
             status = STABLE,
             fname = 'sidebarviews.py',
             authors = [u"Doug Blank"],
             authors_email = ["doug.blank@gmail.com"],
             viewclass = '%sSidebar' % name,
      )
