register(GRAMPLET, 
         id= "Filter Gramplet", 
         name=_("Filter Gramplet"), 
         description = _("Gramplet for controlling filter for a splitview"),
         height=500,
         expand=True,
         gramplet = 'FilterGramplet',
         gramplet_title=_("Filter"),
         status=STABLE,
         version = '1.0.3',
         gramps_target_version = "3.3",
         fname="filtergramplet.py",
         )
