register(GRAMPLET,
         id="House Timeline",
         name=_("House Timeline"),
         description = _("Lists the Residents of an Address by Timeline"),
         version = '1.0.1',
         gramps_target_version="5.0",
         status = STABLE,
         fname="housetimeline.py",
         height = 100,
         expand = True,
         detached_width = 700,
         detached_height = 460,
         gramplet = 'HouseTimelineGramplet',
         gramplet_title=_("House Timeline"),
         help_url='House_Timeline_Gramplet'
         )
