register(GRAMPLET, 
         id="Headline News Gramplet", 
         name=_("Headline News Gramplet"), 
         description = _("Gramplet for showing latest the Gramps news"),
         status = UNSTABLE,
         fname="HeadlineNewsGramplet.py",
         height=300,
         expand=True,
         gramplet = 'HeadlineNewsGramplet',
         gramplet_title=_("Headline News"),
         version = '1.0.11',
         gramps_target_version="3.5",
         )
