register(GRAMPLET,
         id = "DNA",
         name = _("DNA"),
         description = _("Gramplet showing a DNA segment map"),
         status = STABLE,
         fname="dna.py",
         height=100,
         expand=True,
         gramplet = 'DNAGramplet',
         gramplet_title=_("DNA"),
         detached_width = 600,
         detached_height = 450,
         version = '1.0.4',
         gramps_target_version='5.2',
         include_in_listing = False,
         )
