register(GRAMPLET,
         id="Python Gramplet",
         name=_("Python Shell"),
         description = _("Interactive Python interpreter"),
         status = STABLE,
         fname="PythonGramplet.py",
         height=250,
         gramplet = 'PythonGramplet',
         gramplet_title=_("Python Shell"),
         version = '1.0.31',
         gramps_target_version = "5.1",
         help_url="PythonGramplet",
         )
