register(GRAMPLET,
         id="Python Gramplet",
         name=_("Python Shell"),
         description = _("Interactive Python interpreter"),
         status = STABLE,
         audience = DEVELOPER,
         fname="PythonGramplet.py",
         height=250,
         gramplet = 'PythonGramplet',
         gramplet_title=_("Python Shell"),
         version = '1.0.35',
         gramps_target_version = "5.2",
         help_url="PythonGramplet",
         )
