register(GRAMPLET, 
         id= "Clock Gramplet", 
         name=_("Clock Gramplet"), 
         description = _("Gramplet for demonstrating Cairo graphics"),
         height=100,
         expand=False,
         gramplet = 'ClockGramplet',
         gramplet_title=_("Clock"),
         status=STABLE,
         version = '0.0.4',
         gramps_target_version = "3.3",
         fname="ClockGramplet.py",
         help_url="Gramplets#GUI_Interface",
         )
