register(GRAMPLET, 
         id = "Ancestor", 
         name=_("Ancestor"), 
         description = _("Gramplet showing active person's ancestors"),
         status = UNSTABLE,
         fname="ancestor.py",
         height=100,
         expand=True,
         gramplet = 'Ancestor',
         gramplet_title=_("Ancestors"),
         detached_width = 500,
         detached_height = 500,
         version = '1.0.4',
         gramps_target_version="4.1",
         include_in_listing = False,
         navtypes=["Person"],
         )
