register(GRAMPLET, 
         id="Python Gramplet", 
         name=_("Python Gramplet"), 
         description = _("Interactive Python interpreter"),
         status = STABLE, # not yet tested with python 3,
         fname="PythonGramplet.py",
         height=250,
         gramplet = 'PythonGramplet',
         gramplet_title=_("Python Shell"),
         version = '1.0.14',
         gramps_target_version = "4.1",
         help_url="PythonGramplet",
         )
