register(GRAMPLET, 
         id="Python Gramplet", 
         name=_("Python Gramplet"), 
         description = _("Interactive Python interpreter"),
         status = STABLE,
         fname="PythonGramplet.py",
         height=250,
         gramplet = 'PythonGramplet',
         gramplet_title=_("Python Shell"),
         version = '1.0.2',
         gramps_target_version = "3.3",
         help_url="PythonGramplet",
         )
