register(GRAMPLET,
         id = "PlaceUpdate",
         name = _("PlaceUpdate"),
         description = _("Gramplet to manipulate multiple places"),
         status = STABLE,
         version = '1.0.6',
         gramps_target_version = '5.1',
         fname = "PlaceUpdate.py",
         gramplet = 'PlaceUpdate',
         height = 375,
         detached_width = 510,
         detached_height = 520,
         expand = True,
         gramplet_title = _("PlaceUpdate"),
         include_in_listing = True,
         help_url = "http://gramps-project.org/wiki/index.php/PlaceUpdate_Gramplet",
         navtypes=["Place"],
)
