register(GRAMPLET,
         id="Photo Tagging",
         name=_("Photo Tagging"),
         description = _("Gramplet for tagging people in photos"),
         version = '1.0.15',
         gramps_target_version="5.0",
         status = STABLE,
         fname="PhotoTaggingGramplet.py",
         height=400,
         gramplet = 'PhotoTaggingGramplet',
         gramplet_title=_("Photo Tagging"),
         navtypes=["Media"],
         )
