register(GRAMPLET,
         id= "Clock Gramplet",
         name=_("Clock"),
         description = _("Gramplet for demonstrating Cairo graphics"),
         height=100,
         expand=False,
         gramplet = 'ClockGramplet',
         gramplet_title=_("Clock"),
         status = STABLE,
         audience = DEVELOPER,
         version = '0.0.34',
         gramps_target_version = "5.2",
         fname="ClockGramplet.py",
         help_url="Gramplets#GUI_Interface",
         )
