#
# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2026  Douglas S. Blank
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Import genealogy data from a filled Gramps census/event form PDF.

The PDF must have been generated by ``generate_pdf.py``, which embeds a
hidden ``_form_id`` AcroForm field that identifies the form template.  Field
names are reconstructed from the Form addon XML definitions, so the Form addon
must be installed.

Field name convention (mirrors generate_pdf.py):

  ``heading_N``                        — N-th heading attribute value
  ``{role}_{col}_{row}``               — multi-section row data
  ``{role}_{col}_1``                   — person-section data (single row)
  ``{role}_Groom_{col}_1``             — family-section groom data
  ``{role}_Bride_{col}_1``             — family-section bride data

All tokens are run through ``_sanitize()`` to match the names generated by
``generate_pdf.py``.

Note: field names are built from the translated attribute names returned by
``get_section_columns()``.  This matches the PDF field names exactly only
when Gramps is running in English (since the PDF generator does not translate).
"""

import logging
import os
import re

from gramps.gen.const import GRAMPS_LOCALE as glocale
from gramps.gen.db import DbTxn
from gramps.gen.errors import GrampsImportError
from gramps.gen.lib import (
    Attribute,
    Citation,
    Event,
    EventRef,
    EventRoleType,
    EventType,
    Family,
    FamilyRelType,
    Media,
    MediaRef,
    Name,
    NameType,
    Person,
    Source,
    SrcAttribute,
    SrcAttributeType,
    Surname,
)
from gramps.gen.mime import get_type

try:
    _trans = glocale.get_addon_translator(__file__)
except ValueError:
    _trans = glocale.translation
_ = _trans.gettext

LOG = logging.getLogger(__name__)

try:
    from form import (  # noqa: E402
        BRIDE,
        DEFINITION_KEY,
        GROOM,
        ORDER_ATTR,
        get_form_date,
        get_form_headings,
        get_form_ids,
        get_form_sections,
        get_form_title,
        get_form_type,
        get_section_columns,
        get_section_type,
    )
    _FORM_AVAILABLE = True
except ImportError:
    _FORM_AVAILABLE = False

try:
    from importpdf import _copy_to_media_dir
except ImportError:
    _copy_to_media_dir = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sanitize(text):
    """Convert text to a PDF field name token (mirrors generate_pdf.py)."""
    return re.sub(r"[^A-Za-z0-9_]", "_", text).strip("_") or "field"


def _split_name(full):
    """
    Split a full name into (firstname, surname).

    Accepts ``"Surname, Given"`` or ``"Given Surname"`` (last token is surname).
    A single token is treated as surname only.
    """
    full = full.strip()
    if "," in full:
        surname, _, firstname = full.partition(",")
        return (firstname.strip(), surname.strip())
    parts = full.split()
    if not parts:
        return ("", "")
    if len(parts) == 1:
        return ("", parts[0])
    return (" ".join(parts[:-1]), parts[-1])


def _make_person(db, trans, name_str):
    """Create and add a Person with *name_str* as primary name; return Person."""
    person = Person()
    if name_str:
        firstname, surname = _split_name(name_str)
        gramps_name = Name()
        gramps_name.set_type(NameType(NameType.BIRTH))
        surn = Surname()
        surn.set_surname(surname)
        gramps_name.add_surname(surn)
        gramps_name.set_first_name(firstname)
        person.set_primary_name(gramps_name)
    db.add_person(person, trans)
    return person


def _add_event_ref_attrs(citation, event_ref, col_names, row_fields):
    """
    Append non-empty column values from *row_fields* as Attributes on *event_ref*.

    *col_names* is the ordered list of translated attribute names.
    *row_fields* maps col_name → value string.
    """
    for col_name in col_names:
        val = row_fields.get(col_name, "")
        if val:
            attr = Attribute()
            attr.set_type(col_name)
            attr.set_value(val)
            attr.add_citation(citation.handle)
            event_ref.add_attribute(attr)


# ---------------------------------------------------------------------------
# Core import logic (accepts pre-extracted fields dict)
# ---------------------------------------------------------------------------

def _import_form_data(dbase, fields, user):
    """
    Import Form PDF data from an already-extracted *fields* dict.

    Called by ``importpdf.importData`` after it detects a non-pedigree
    ``_form_id`` field.
    """
    if not _FORM_AVAILABLE:
        user.notify_error(
            _("Form addon required"),
            _("The Form addon must be installed to import Form PDF files.\n"
              "Please install the Form addon and restart Gramps.")
        )
        return

    form_id = fields.get("_form_id", "").strip()
    if not form_id:
        user.notify_error(
            _("Not a Form PDF"),
            _("The _form_id field is missing or empty.")
        )
        return

    known_ids = list(get_form_ids())
    if form_id not in known_ids:
        user.notify_error(
            _("Unknown form ID"),
            _("Form ID '%(id)s' is not recognised by the Form addon.\n"
              "Known IDs: %(known)s") % {
                  "id": form_id,
                  "known": ", ".join(sorted(known_ids)),
              }
        )
        return

    LOG.info("Importing Form PDF: form_id=%s", form_id)

    form_title   = get_form_title(form_id)
    headings     = get_form_headings(form_id)   # translated heading names
    section_list = get_form_sections(form_id)   # ordered list of role strings
    form_date    = get_form_date(form_id)        # Date object or None
    form_type    = get_form_type(form_id)        # EventType xml_str

    name_col = _("Name")

    pdf_filename = fields.get("_pdf_filename", "")
    _stored_path = None
    if pdf_filename and _copy_to_media_dir:
        _stored_path = _copy_to_media_dir(dbase, pdf_filename)

    with DbTxn(_("Import Form PDF: %s") % form_title, dbase) as trans:

        # ── Media ────────────────────────────────────────────────────────────
        _media = None
        if pdf_filename and _stored_path:
            _media = Media()
            _media.set_path(_stored_path)
            _media.set_mime_type(get_type(pdf_filename))
            _media.set_description(os.path.basename(pdf_filename))
            dbase.add_media(_media, trans)

        def _media_ref():
            ref = MediaRef()
            ref.set_reference_handle(_media.handle)
            return ref

        # ── Source ──────────────────────────────────────────────────────────
        source = Source()
        source.set_title(form_title)
        src_attr = SrcAttribute()
        src_attr.set_type(SrcAttributeType(DEFINITION_KEY))
        src_attr.set_value(form_id)
        source.add_attribute(src_attr)
        dbase.add_source(source, trans)

        # ── Citation ────────────────────────────────────────────────────────
        citation = Citation()
        citation.set_reference_handle(source.handle)
        page_parts = [
            "%s: %s" % (h, v)
            for i, h in enumerate(headings)
            for v in [fields.get("heading_%d" % i, "")]
            if v
        ]
        citation.set_page("; ".join(page_parts))
        dbase.add_citation(citation, trans)

        # ── Event ────────────────────────────────────────────────────────────
        event = Event()
        event_type = EventType()
        event_type.set_from_xml_str(form_type)
        event.set_type(event_type)
        if form_date is not None:
            event.set_date_object(form_date)
        event.add_citation(citation.handle)

        for i, heading in enumerate(headings):
            val = fields.get("heading_%d" % i, "")
            if val:
                attr = Attribute()
                attr.set_type(heading)
                attr.set_value(val)
                attr.add_citation(citation.handle)
                event.add_attribute(attr)

        if _media:
            event.add_media_reference(_media_ref())
        dbase.add_event(event, trans)

        # ── Sections ─────────────────────────────────────────────────────────
        for role in section_list:
            stype     = get_section_type(form_id, role)
            columns   = get_section_columns(form_id, role)   # [(attr, long, size)]
            col_names = [c[0] for c in columns]              # translated names
            role_san  = _sanitize(role)

            event_role = EventRoleType()
            event_role.set_from_xml_str(role)

            # ── multi: one Person per non-empty row ───────────────────────
            if stype == "multi":
                row_num = 1
                while True:
                    first_fname = _sanitize(
                        "%s_%s_%d" % (role_san, col_names[0], row_num)
                    )
                    if first_fname not in fields:
                        break

                    row_fields = {
                        col: fields.get(
                            _sanitize("%s_%s_%d" % (role_san, col, row_num)), ""
                        )
                        for col in col_names
                    }

                    if any(row_fields.values()):
                        person = _make_person(
                            dbase, trans, row_fields.get(name_col, "")
                        )

                        event_ref = EventRef()
                        event_ref.ref = event.handle
                        event_ref.set_role(event_role)

                        order_attr = Attribute()
                        order_attr.set_type(ORDER_ATTR)
                        order_attr.set_value(str(row_num))
                        order_attr.add_citation(citation.handle)
                        order_attr.set_privacy(True)
                        event_ref.add_attribute(order_attr)

                        _add_event_ref_attrs(
                            citation, event_ref, col_names, row_fields
                        )

                        person.add_event_ref(event_ref)
                        if _media:
                            person.add_media_reference(_media_ref())
                        dbase.commit_person(person, trans)

                    row_num += 1

            # ── person: single Person for this role ───────────────────────
            elif stype == "person":
                row_fields = {
                    col: fields.get(
                        _sanitize("%s_%s_1" % (role_san, col)), ""
                    )
                    for col in col_names
                }

                if not any(row_fields.values()):
                    continue

                person = _make_person(
                    dbase, trans, row_fields.get(name_col, "")
                )

                event_ref = EventRef()
                event_ref.ref = event.handle
                event_ref.set_role(event_role)
                _add_event_ref_attrs(
                    citation, event_ref, col_names, row_fields
                )

                person.add_event_ref(event_ref)
                if _media:
                    person.add_media_reference(_media_ref())
                dbase.commit_person(person, trans)

            # ── family: one Family with Groom + Bride sub-groups ──────────
            elif stype == "family":
                groom_fields = {
                    col: fields.get(
                        _sanitize("%s_Groom_%s_1" % (role_san, col)), ""
                    )
                    for col in col_names
                }
                bride_fields = {
                    col: fields.get(
                        _sanitize("%s_Bride_%s_1" % (role_san, col)), ""
                    )
                    for col in col_names
                }

                if not any(groom_fields.values()) and not any(bride_fields.values()):
                    continue

                family = Family()
                family.set_relationship(FamilyRelType(FamilyRelType.MARRIED))
                dbase.add_family(family, trans)

                if any(groom_fields.values()):
                    husband = _make_person(
                        dbase, trans, groom_fields.get(name_col, "")
                    )
                    husband.add_family_handle(family.handle)
                    family.set_father_handle(husband.handle)
                    if _media:
                        husband.add_media_reference(_media_ref())
                    dbase.commit_person(husband, trans)

                if any(bride_fields.values()):
                    wife = _make_person(
                        dbase, trans, bride_fields.get(name_col, "")
                    )
                    wife.add_family_handle(family.handle)
                    family.set_mother_handle(wife.handle)
                    if _media:
                        wife.add_media_reference(_media_ref())
                    dbase.commit_person(wife, trans)

                # Attributes use GROOM/BRIDE prefixes (matches editform.py).
                event_ref = EventRef()
                event_ref.ref = event.handle
                event_ref.set_role(event_role)

                for col_name in col_names:
                    for prefix, row_fields in (
                        (GROOM, groom_fields),
                        (BRIDE, bride_fields),
                    ):
                        val = row_fields.get(col_name, "")
                        if val:
                            attr = Attribute()
                            attr.set_type("%s %s" % (prefix, col_name))
                            attr.set_value(val)
                            attr.add_citation(citation.handle)
                            event_ref.add_attribute(attr)

                family.add_event_ref(event_ref)
                dbase.commit_family(family, trans)

    LOG.info("Form PDF import complete: form_id=%s", form_id)
