files: ^ChatWithTree/
exclude: ^ChatWithTree/ChatWithTree.gpr.py
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
    - id: check-yaml
      args: [--unsafe]
    - id: check-added-large-files
    - id: check-json
    - id: pretty-format-json
      args: [--autofix]
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-private-key
    - id: mixed-line-ending
      args: [--fix=lf]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  -   id: isort
- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  -   id: flake8
      args  : [--max-line-length=89]
