register(GRAMPLET,
         id = "PlaceTool",
         name = _("PlaceTool"),
         description = _("Gramplet to manipulate multiple places"),
         status = STABLE,
         version = '1.0.0',
         gramps_target_version = '5.1',
         fname = "PlaceTool.py",
         gramplet = 'PlaceTool',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("PlaceTool"),
         include_in_listing = True,
         navtypes=["Place"],
        )
