register(GRAMPLET,
         id = "FamilyTree DNA Import Gramplet",
         name = _("FamilyTree DNA"),
         description = _("Gramplet to import FamilyFinder dna data from Family Tree"),
         status = STABLE,
         audience = EXPERT,
         version = '1.0.20',
         gramps_target_version = '5.2',
         fname = "ftdna_import.py",
         gramplet = 'FamilyTreeDNA',
         height = 375,
         detached_width = 510,
         detached_height = 480,
         expand = True,
         gramplet_title = _("FamilyTree DNA"),
         help_url="FamilyTree DNA Gramplet",
         include_in_listing = True,
        )
