<?xml version='1.0' encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<!--
   ===================================================================
GNU General Public License 2, or (at your option) any later version.
   ===================================================================

print(etree.tostring(xml, encoding="UTF-8")) for getting the custom structure

<query lang="fr-FR" title="I am looking at ..." footer="Content generated by Gramps"
date="30/03/2025" first="26 juillet 2007" last="27 janvier 2025">
   <clist pname="Nom" country="Pays">
      <country></country>
      <country>Australia</country>
      <country>Brazil</country>
      <country>Bulgarie</country>
      ...
   </clist>
   <log date="2025-03-18" version="6.0.0"/>
   <surnames title="Noms de famille">
      <surname>Abbott</surname>
      ...
   <places pname="Lieux">
      <place>AK - (? or fr)</place>
      <place>AK, USA</place>
      <place>AL - (? or fr)</place>
      <place>AL, USA</place>
      <place>AR - (? or fr)</place>
      ...
      <place>\xce\xa3\xce\xb9\xce\xac\xcf\x84\xce\xb9\xcf\x83\xcf\x84\xce\xb1 - (el)</place>
   </places>
   <sources title="List of sources">
      <source>All possible citations</source>
      <source>Baptize registry 1850 - 1867 Great Falls Church</source>
      <source>Import from test2.ged</source>
      <source>World of the Wierd</source>
   </sources>
</query>

-->
<xsl:output method='text'/>

<xsl:variable name="surname-count" select="count(query/surnames/surname)"/>
<xsl:variable name="place-count" select="count(query/places/place)"/>

<xsl:template match="/">

<xsl:for-each select="query/surnames/surname">
   <xsl:text>{"surname":"</xsl:text>
      <xsl:value-of select="."/>
   <xsl:text>"}&#xa;</xsl:text>
</xsl:for-each>
<xsl:for-each select="query/places/place">
   <xsl:text>{"place":"</xsl:text>
      <xsl:value-of select="."/>
      <xsl:text>","lang":"</xsl:text>
   <xsl:text>"}&#xa;</xsl:text>
</xsl:for-each>
<xsl:for-each select="query/sources/source">
   <xsl:text>{"source":"</xsl:text>
      <xsl:value-of select="."/>
   <xsl:text>"}&#xa;</xsl:text>
</xsl:for-each>
<xsl:text>&#xa;</xsl:text>
</xsl:template>
</xsl:stylesheet>
